email: info@unaiabrisketa.com
url: 'http://localhost'
twitter_username: unabris
github_username:  unabris

sass:
  sass_dir: _sass
  style: compressed

include:
- _pages

markdown: kramdown

plugins:
- neat
- bourbon

exclude:
- Gemfile
- Gemfile.lock
- vendor
- Procfile
