email: info@unaiabrisketa.com
description: ''
baseurl: ''
url: 'http://localhost'
port: 3000
twitter_username: unabris
github_username:  unabris

sass:
  sass_dir: _sass
  style: compressed

include:
- _pages

markdown: kramdown

plugins:
- neat
- bourbon
- jekyll-feed

exclude:
- Gemfile
- Gemfile.lock
- vendor
