email: info@unaiabrisketa.com
url: 'http://www.unaiabrisketa.com'
twitter_username: unabris
github_username:  unabris

recaptcha_key: 6LfnVRUUAAAAALZCu3PVN5sADJLGOWpdNxMgx9eT

sass:
  sass_dir: _sass
  style: compressed

include:
- _pages

markdown: kramdown

plugins:
- neat
- bourbon

exclude:
- Gemfile
- Gemfile.lock
- vendor
- Procfile
- circle.yml
- Rakefile
